namespace: event-triangle-dev

entra_id_auth_secret: "My_3nt4ra_s3cr3t"
rabbit_mq_host: "rabbitmq-cluster.rabbitmq-dev.svc"
redis_url: "redis-server-dev-master.redis-dev.svc"
redis_password: "Rx9nJ781GMe5"

postgres_host: "pgsql-dev-service.pgsql-dev.svc"
postgres_user: "postgres"
postgres_password: "s8SefXkZZlqd"
