---
kind: Service
apiVersion: v1
metadata:
  name: sender-api-service
spec:
  selector:
    app: sender-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #NodePort