---
kind: Service
apiVersion: v1
metadata:
  name: event-triangle-sender-service
  namespace: event-triangle
spec:
  selector:
    app: event-triangle-sender-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: grpc
      protocol: TCP
      port: 81
      targetPort: 81
  type: ClusterIP
