apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.environment | quote }}
