apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SenderDatabaseConnectionString: "Server={{ .Values.postgres_host }};User Id={{ .Values.postgres_user }};Password={{ .Values.postgres_password }};Database=SenderDb;"
  RabbitMqHost: {{ .Values.rabbit_mq_host | quote }}
  RabbitMqUsername: {{ .Values.rabbitmq_username | quote }}
  RabbitMqPassword: {{ .Values.rabbitmq_password | quote }}
