apiVersion: v1
kind: Service
metadata:
  name: event-triangle-sender-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ .Values.service.type }}
