apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: razumovsky-me
  namespace: event-triangle
spec:
  secretName: razumovsky-me-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.eventtriangle.razumovsky.me