---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  labels:
    app: auth-api
data:
  EVENT_TRIANGLE_AD_CLIENT_SECRET: ""
  DatabaseConnectionString: "Server=<IP>;User Id=postgres;Password=postgres;Database=AuthorizationDb;"