apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: RabbitMqHost
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: RabbitMqHost
            - name: RabbitMqUsername
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: RabbitMqUsername
            - name: RabbitMqPassword
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: RabbitMqPassword
            - name: DatabaseConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: ConsumerDatabaseConnectionString
