apiVersion: v1
kind: Service
metadata:
  name: event-triangle-consumer-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.targetPort }}
  type: ClusterIP
