---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-service-deployment
spec:
  selector:
    matchLabels:
      app: sender-service
  replicas: 3
  template:
    metadata:
      labels:
        app: sender-service
    spec:
      containers:
        - name: sender-service-api
          image: kaminome/sender-service:0.3.0-alpha.235
          ports:
            - containerPort: 80
          env:
            - name: DatabaseConnectionString
              valueFrom:
                configMapKeyRef:
                  name: sender-configmap
                  key: DatabaseConnectionString