---
kind: Service
apiVersion: v1
metadata:
  name: sender-service-api
spec:
  selector:
    app: sender-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #NodePort