trigger: none

pr:
  autoCancel: true  
  branches:
    include:
      - develop
      - main

  paths:
    include:
      # Auth service (ALL layers)
      - src/authorization/**

      # Shared code used by auth
      - src/shared/**

      # Pipeline itself (so changes validate)
      - azure-pipelines/**
      - azure-pipelines/templates/**

    exclude:
      # Docs
      - '**/*.md'

      # Docker compose (global/dev only)
      - '**/docker-compose*.yml'
      - '**/docker-compose*.yaml'

      # Ignore other services explicitly
      - src/consumer/**
      - src/sender/**

      # Helm & infra (unless auth-specific)
      - helm/**
      - platform/**
      - cloudflare/**
      - docs/**
      - kubernetes/**
      - img/**
      - terraform/**
      - terraform-azdo-libraries/**
      - .github/**
      - LICENSE

variables:
  - name: appName
    value: 'AuthorizationAPI'
  - name: System.Debug
    value: 'false'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'PR_Validation_${{ variables.appName }}'
    displayName: 'PR_Validation_${{ variables.appName }}'
    jobs:
      - template: ../templates/docker-build-push-jobs.yml
        parameters:
          JobName: 'PR_Validation_${{ variables.appName }}'
          solution: '$(System.DefaultWorkingDirectory)/EventTriangleAPI.sln'
          buildConfiguration: 'Release'
          backendProjectPath: '$(System.DefaultWorkingDirectory)/src/authorization/EventTriangleAPI.Authorization.Presentation'
          shouldRunUnitTests: false
          shouldRunIntegrationTests: true
          integrationTestsProjectPath: '$(System.DefaultWorkingDirectory)/src/authorization/EventTriangleAPI.Authorization.IntegrationTests/EventTriangleAPI.Authorization.IntegrationTests.csproj'
          dockerRegistryUrl: 'docker.io/kaminome'
          dockerBuildParameterUrl: 'https://auth-eventtriangle.razumovsky.me/'
          imageRepository: 'auth-service'
          dockerfilePath: '$(System.DefaultWorkingDirectory)/src/authorization/Dockerfile'
          dockerServiceConnection: 'Docker_Hub_Connection'
          shouldPushToAcr: true
          acrRegistryUrl: 'acrsharedd01.azurecr.io'
          acrServiceConnection: 'Azure_ACR_Connection'
          workingDirectoryForDocker: '$(System.DefaultWorkingDirectory)/src'
