apiVersion: v1
kind: Secret
metadata:
  name: connection-creds
  namespace: event-triangle
type: Opaque
stringData: # takes plain text secrets
  EVENT_TRIANGLE_AD_CLIENT_SECRET: "{{library-azure-ad-secret}}"
  SenderDatabaseConnectionString: "Server=db;User Id={{POSTGRES_USER}};Password={{POSTGRES_PASSWORD}};Database=SenderDb;"
  AuthDatabaseConnectionString: "Server=db;User Id={{POSTGRES_USER}};Password={{POSTGRES_PASSWORD}};Database=AuthorizationDb;"
  ConsumerDatabaseConnectionString: "Server=db;User Id={{POSTGRES_USER}};Password={{POSTGRES_PASSWORD}}};Database=ConsumerDb;"
  RabbitMqHost: "event-rabbitmq"
  POSTGRES_USER: "{{POSTGRES_USER}}"
  POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
  POSTGRES_DB: "{{POSTGRES_DB}}"