apiVersion: v1
kind: Secret
metadata:
  name: connection-creds
type: Opaque
#data: -- requires base 64 secrets
stringData: # takes plain text secrets
  EVENT_TRIANGLE_AD_CLIENT_SECRET: "<YOUR_SECRET_HERE>"
  DatabaseConnectionString: "<DATABASE_CONNECTION_STRING_HERE>"
  RabbitMqHost: "<RABBITMQ_HOST_IP_HERE>"