apiVersion: v1
kind: Secret
metadata:
  name: connection-creds
  namespace: event-triangle
type: Opaque
stringData: # takes plain text secrets
  EVENT_TRIANGLE_AD_CLIENT_SECRET: "{{library-azure-ad-secret}}"
  SenderDatabaseConnectionString: "Server=db;User Id={{library-postgres-user}};Password={{library-postgres-password}};Database=SenderDb;"
  AuthDatabaseConnectionString: "Server=db;User Id={{library-postgres-user}};Password={{library-postgres-password}};Database=AuthorizationDb;"
  ConsumerDatabaseConnectionString: "Server=db;User Id={{library-postgres-user}};Password={{library-postgres-password}};Database=ConsumerDb;"
  RabbitMqHost: "event-rabbitmq"
  POSTGRES_USER: "{{library-postgres-user}}"
  POSTGRES_PASSWORD: "{{library-postgres-password}}"
  RabbitMqUser: "{{library-rabbitmq-user}}"
  RabbitMqPassword: "{{library-rabbitmq-password}}"