apiVersion: v1
kind: Secret
metadata:
  name: connection-creds
  namespace: event-triangle
type: Opaque
#data: -- requires base 64 secrets
stringData: # takes plain text secrets
  EVENT_TRIANGLE_AD_CLIENT_SECRET: "<REPLACE_AD_SECRET>"
  SenderDatabaseConnectionString: "Server=db;User Id=postgres;Password=postgres;Database=SenderDb;"
  AuthDatabaseConnectionString: "Server=db;User Id=postgres;Password=postgres;Database=AuthorizationDb;"
  ConsumerDatabaseConnectionString: "Server=db;User Id=postgres;Password=postgres;Database=ConsumerDb;"
  RabbitMqHost: "event-rabbitmq"