---
kind: Service
apiVersion: v1
metadata:
  name: event-triangle-auth-service
spec:
  selector:
    app: event-triangle-auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #NodePort
