---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume
  namespace: event-triangle
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
