---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-triangle-sender-deployment
spec:
  selector:
    matchLabels:
      app: event-triangle-sender-api
  replicas: 1
  template:
    metadata:
      labels:
        app: event-triangle-sender-api
    spec:
      containers:
        - name: event-triangle-sender-api
          image: kaminome/sender-service:0.1.3-PullRequest0076.247
          ports:
            - containerPort: 80
            - containerPort: 81
          env:
            - name: RabbitMqHost
              valueFrom:
                configMapKeyRef:
                  name: event-triangle-sender-configmap
                  key: RabbitMqHost

            - name: DatabaseConnectionString
              valueFrom:
                configMapKeyRef:
                  name: event-triangle-sender-configmap
                  key: DatabaseConnectionString
