---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-triangle-auth-deployment
  namespace: event-triangle
spec:
  selector:
    matchLabels:
      app: event-triangle-auth-api
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # Create at most 1 extra pod during update
      maxUnavailable: 1  # At most 1 pod can be unavailable
  template:
    metadata:
      labels:
        app: event-triangle-auth-api
    spec:
      containers:
        - name: event-triangle-auth-api
          image: kaminome/auth-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
            - containerPort: 81
          env:
            - name: EVENT_TRIANGLE_AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: connection-creds
                  key: EVENT_TRIANGLE_AD_CLIENT_SECRET

            - name: DatabaseConnectionString
              valueFrom:
                secretKeyRef:
                  name: connection-creds
                  key: AuthDatabaseConnectionString

            - name: RedisUrl
              valueFrom:
                secretKeyRef:
                  name: connection-creds
                  key: RedisUrl

            - name: RedisPassword
              valueFrom:
                secretKeyRef:
                  name: connection-creds
                  key: RedisPassword

            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
