apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
