apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  EVENT_TRIANGLE_AD_CLIENT_SECRET: {{ .Values.entra_id_auth_secret | quote }}
  AuthDatabaseConnectionString: "Server={{ .Values.postgres_host }};User Id={{ .Values.postgres_user }};Password={{ .Values.postgres_password }};Database=AuthorizationDb;"
  RabbitMqHost: {{ .Values.rabbit_mq_host | quote }}
  RedisUrl: {{ .Values.redis_url | quote }}
  RedisPassword: {{ .Values.redis_password | quote }}
