namespace: event-triangle
replicaCount: 1

image:
  repository: kaminome/consumer-service
  tag: latest
  pullPolicy: Always

ports:
  containerPort: 80
  servicePort: 80
  targetPort: 8080

env:
  RabbitMqHost:
    secretName: connection-creds
    key: RabbitMqHost

  RabbitMqUsername:
    secretName: connection-creds
    key: RabbitMqUsername

  RabbitMqPassword:
    secretName: connection-creds
    key: RabbitMqPassword

  DatabaseConnectionString:
    secretName: connection-creds
    key: ConsumerDatabaseConnectionString

  ASPNETCORE_ENVIRONMENT:
    configMapName: consumer-service-chart-configmap
    key: ASPNETCORE_ENVIRONMENT

configMap:
  ASPNETCORE_ENVIRONMENT: Docker
