namespace: event-triangle
replicaCount: 1

image:
  repository: kaminome/consumer-service
  tag: latest
  pullPolicy: Always

ports:
  containerPort: 80
  servicePort: 80
  targetPort: 8080

env:
  RabbitMqHost:
    secretName: event-rabbitmq-default-user
    key: host

  RabbitMqUsername:
    secretName: event-rabbitmq-default-user
    key: username

  RabbitMqPassword:
    secretName: event-rabbitmq-default-user
    key: password

  DatabaseConnectionString:
    secretName: connection-creds
    key: ConsumerDatabaseConnectionString
