namespace: event-triangle-dev
replicaCount: 1

image:
  repository: kaminome/consumer-service
  tag: latest
  pullPolicy: Always

rabbit_mq_host: "rabbitmq-cluster.rabbitmq-dev.svc"
rabbitmq_username: "rabbitmq-user"
rabbitmq_password: "myPa55w0rd"


postgres_host: "pgsql-dev-service.pgsql-dev.svc"
postgres_user: "postgres"
postgres_password: "s8SefXkZZlqd"

ports:
  containerPort: 80
  servicePort: 80
  targetPort: 8080
