apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.username }}
  POSTGRES_PASSWORD: {{ .Values.password }}
  POSTGRES_DB: postgres
