trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/cloudflare/**
      - .azdo/cloudflare/**
      - .azdo/templates/terraform-*.yml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/cloudflare/**
      - .azdo/cloudflare/**
      - .azdo/templates/terraform-*.yml

variables:
  - group: Cloudflare_API_Key
  - group: Terraform_Backend_StateFile_Settings
  - name: terraformVersion
    value: '1.16.0'
  - name: workingDirectory
    value: '$(System.DefaultWorkingDirectory)/terraform/cloudflare/environments/dev'
  - name: cloudflareStateFile
    value: 'cloudflare-dev.tfstate'
  - name: planStageName
    value: 'Cloudflare_Plan'
  - name: applyStageName
    value: 'Cloudflare_Apply'

stages:
  - template: ../templates/terraform-plan-stages.yml
    parameters:
      stageName: ${{ variables.planStageName }}
      vmImage: ubuntu-latest
      terraformVersion: $(terraformVersion)
      terraformBasePath: $(System.DefaultWorkingDirectory)/terraform/cloudflare
      workingDirectory: $(workingDirectory)
      storageAccount: $(library-storage-account)
      storageContainer: $(library-storage-container)
      stateFile: $(cloudflareStateFile)
      sasToken: $(library-sas-token)
      destroy: false
      terraformEnvironment:
        CLOUDFLARE_API_TOKEN: $(cloudflare-api-key)

  - template: ../templates/terraform-apply-stages.yml
    parameters:
      stageName: ${{ variables.applyStageName }}
      vmImage: ubuntu-latest
      terraformVersion: $(terraformVersion)
      workingDirectory: $(workingDirectory)
      storageAccount: $(library-storage-account)
      storageContainer: $(library-storage-container)
      stateFile: $(cloudflareStateFile)
      sasToken: $(library-sas-token)
      environment: dev
      dependsOn: [ '${{ variables.planStageName }}' ]
      condition: ${{ variables.planStageName }}
      additionalCondition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      terraformEnvironment:
        CLOUDFLARE_API_TOKEN: $(cloudflare-api-key)
