---
kind: Service
apiVersion: v1
metadata:
  name: consumer-service
spec:
  selector:
    app: event-triangle-consumer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
