name: Build And Test Auth API
on:
  push:
    branches:
      - develop
      - main
    paths:
      - src/sender/EventTriangleAPI.Authorization.BusinessLogic/**
      - src/sender/EventTriangleAPI.Authorization.Presentation/**
      - src/shared/EventTriangleAPI.Shared.DTO/**
      - src/shared/EventTriangleAPI.Shared.Application/**
      - .github/**

  pull_request:
    branches:
      - develop
      - main
    paths:
      - src/sender/EventTriangleAPI.Authorization.BusinessLogic/**
      - src/sender/EventTriangleAPI.Authorization.Presentation/**
      - src/shared/EventTriangleAPI.Shared.DTO/**
      - src/shared/EventTriangleAPI.Shared.Application/**
      - .github/**

  workflow_dispatch:

jobs:
  build-and-test-dotnet:
    name: Auth Build
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auth Build
        uses: ./.github/actions/build-and-test
        with:
          backendCsprojPath: "src/authorization/EventTriangleAPI.Authorization.Presentation/EventTriangleAPI.Authorization.Presentation.csproj"
          buildConfiguration: "Release"
          serviceName: "auth-api"
          unitTestsProjectPath: "src/authorization/EventTriangleAPI.Authorization.UnitTests"
          creatingDatabase: 'true'
