name: Docker compose build

on: 
  push:
    branches:
      - main
      - develop
  pull_request: 
    branches: [ develop ]
  workflow_dispatch:
  
jobs:
  angular-build:
    name: Docker compose build
    runs-on: ${{ matrix.environment }}
    strategy: 
      matrix:
        environment:
          - ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Docker compose build
        run: |
          docker compose build