name: Build And Test Consumer API 

on:
  push:
    branches:
      - develop
      - main
    paths:
      - src/consumer/EventTriangleAPI.Consumer.Application/**
      - src/consumer/EventTriangleAPI.Consumer.BusinessLogic/**
      - src/consumer/EventTriangleAPI.Consumer.Domain/**
      - src/consumer/EventTriangleAPI.Consumer.IntegrationTests/**
      - src/consumer/EventTriangleAPI.Consumer.Presentation/**
      - src/consumer/EventTriangleAPI.Consumer.UnitTests/**
      - .github/**

  pull_request:
    branches:
      - develop
      - main
    paths:
      - src/consumer/EventTriangleAPI.Consumer.Application/**
      - src/consumer/EventTriangleAPI.Consumer.BusinessLogic/**
      - src/consumer/EventTriangleAPI.Consumer.Domain/**
      - src/consumer/EventTriangleAPI.Consumer.IntegrationTests/**
      - src/consumer/EventTriangleAPI.Consumer.Presentation/**
      - src/consumer/EventTriangleAPI.Consumer.UnitTests/**
      - src/shared/EventTriangleAPI.Shared.DTO/**
      - src/shared/EventTriangleAPI.Shared.Application/**
      - .github/**

  workflow_dispatch:

jobs:
  build-and-test-dotnet:
    name: Build Test Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          backendCsprojPath: "src/consumer/EventTriangleAPI.Consumer.Presentation/EventTriangleAPI.Consumer.Presentation.csproj"
          unitTestsProjectPath: "src/consumer/EventTriangleAPI.Consumer.UnitTests"
          integrationTestsProjectPath: "src/consumer/EventTriangleAPI.Consumer.IntegrationTests"
          buildConfiguration: "Release"