parameters:
  - name: JobName
    displayName: 'Job Name'
    type: string

  - name: workingDirectoryForDocker
    displayName: 'Working directory for Docker Build'
    default: '$(System.DefaultWorkingDirectory)/src'
    type: string

  - name: gitVersionVersion
    displayName: 'GitVersion version'
    default: '6.x'
    type: string

  - name: dockerRegistryUrl
    type: string
    displayName: 'DockerHub Registry URL. For Docker Hub it is: docker.io/kaminome.'

  - name: shouldPushToDockerHub
    type: boolean
    default: false

  - name: shouldPushToAcr
    type: boolean
    default: false

  - name: acrRegistryUrl
    type: string
    displayName: 'ACR Registry URL. For ACR it is FQDN URL of container registry: azuredevopsacrd01.azurecr.io'

  - name: imageRepository
    displayName: 'Image Repository name'
    type: string

  - name: dockerfilePath
    displayName: 'Dockerfile path'
    type: string

  - name: dockerServiceConnection
    displayName: 'DockerHub service connection in Azure DevOps.'
    type: string

  - name: acrServiceConnection
    displayName: 'Azure container registry service connection in Azure DevOps.'
    type: string

jobs:
  - job: ${{ parameters.JobName }}
    displayName: ${{ parameters.JobName }}
    steps:
      - checkout: self
        fetchDepth: 0

      - task: gitversion-setup@4.5.0
        displayName: 'GitVersion Setup'
        condition: succeeded()
        inputs:
          versionSpec: ${{ parameters.gitVersionVersion }}

      - task: gitversion-execute@4.5.0
        name: version_step # step id used as a reference for output values
        displayName: Determine Version
        condition: succeeded()

      - bash: echo $Action$BuildVersion
        displayName: 'Set Build Version'
        condition: succeeded()
        env:
          Action: '##vso[build.updatebuildnumber]'
          BuildVersion: $(version_step.semVer)

      - pwsh: |
          Write-Host "=== ENV VARIABLES ==="
          Get-ChildItem Env: | Sort-Object Name

          Write-Host "=== PIPELINE VARIABLES ==="
          Write-Host "FullSemVer: $(version_step.FullSemVer)"
          Write-Host "SemVer: $(version_step.SemVer)"
          Write-Host "ShortSha: $(version_step.ShortSha)"
          Write-Host "Build Source branch: $env:BUILD_SOURCEBRANCHNAME"
        displayName: Debug environment
        condition: succeeded()

      - task: PowerShell@2
        displayName: 'Build Docker Image'
        condition: succeeded()
        inputs:
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)/scripts/Build-Docker.ps1'
          arguments: "-DockerRegistryUrl ${{ parameters.dockerRegistryUrl }}
                      -ImageRepository ${{ parameters.imageRepository }}
                      -AcrRegistryUrl ${{ parameters.acrRegistryUrl }}
                      -DockerfilePath ${{ parameters.dockerfilePath }}
                      -GitVersion $(version_step.semVer)
                      -WorkingDirectory ${{ parameters.workingDirectoryForDocker }}
                      -CommitSha $(version_step.ShortSha)"
          errorActionPreference: 'stop'
          pwsh: true

      - task: Docker@2
        displayName: 'Push to DockerHub'
        condition: and(succeeded(), eq(${{ parameters.shouldPushToDockerHub }}, true))
        inputs:
          command: push
          containerRegistry: ${{ parameters.dockerServiceConnection }}
          repository: ${{ parameters.dockerRegistryUrl }}/${{ parameters.imageRepository }}
          tags: |
            $(version_step.semVer)
            $(version_step.semVer)-$(version_step.ShortSha)
            latest

      - task: Docker@2
        displayName: 'Push to ACR'
        condition: and(succeeded(), eq(${{ parameters.shouldPushToAcr }}, true))
        inputs:
          command: push
          containerRegistry: ${{ parameters.acrServiceConnection }}
          repository: ${{ parameters.imageRepository }}
          tags: |
            $(version_step.semVer)
            $(version_step.semVer)-$(version_step.ShortSha)
            latest
