parameters:
  - name: jobName
    displayName: 'Job Name'
    type: string

  - name: gitVersionVersion
    displayName: 'GitVersion version'
    default: '6.x'
    type: string

  - name: registryUrl
    type: string
    displayName: >
      ACR Registry URL.
      For ACR it is FQDN URL of container registry: azuredevopsacrd01.azurecr.io.
      For Docker Hub it is: docker.io/petrkolosov.

  - name: imageRepository
    displayName: 'Image Repository name'
    type: string

  - name: dockerfilePath
    displayName: 'Dockerfile path'
    type: string

  - name: dockerServiceConnection
    displayName: 'Azure container registry service connection in Azure DevOps.'
    type: string

  - name: scriptFile
    displayName: Docker build script path
    type: string

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    steps:
      - checkout: self
        fetchDepth: 0

      - task: gitversion-setup@4.5.0
        displayName: 'GitVersion Setup'
        condition: succeeded()
        inputs:
          versionSpec: ${{ parameters.gitVersionVersion }}

      - task: gitversion-execute@4.5.0
        name: version_step # step id used as a reference for output values
        displayName: Determine Version
        condition: succeeded()

      - bash: echo $Action$BuildVersion
        displayName: 'Set Build Version'
        condition: succeeded()
        env:
          Action: '##vso[build.updatebuildnumber]'
          BuildVersion: $(version_step.semVer)

      - bash: |
          echo "=== ENV VARIABLES ==="
          printenv

          echo "=== PIPELINE VARIABLES ==="
          echo "FullSemVer: $(version_step.FullSemVer)"
          echo "SemVer: $(version_step.SemVer)"
          echo "ShortSha: $(version_step.ShortSha)"
          echo "Build Source branch: $BUILD_SOURCEBRANCHNAME"
        displayName: Debug Environment
        condition: succeeded()

      - bash: |
          cd ./scripts
          chmod +x docker-inspect.sh
          ./docker-inspect.sh
        displayName: Docker Inspect
        condition: succeeded()

      - task: Docker@2
        displayName: "Docker Login"
        inputs:
          command: login
          containerRegistry: ${{ parameters.acrServiceConnection }}

      - bash: |
          set -euo pipefail
          SCRIPT_FILE="${{ parameters.scriptFile }}"
          echo "Script file: ${SCRIPT_FILE}"
          chmod +x "${SCRIPT_FILE}"
          "${SCRIPT_FILE}" $(version_step.SemVer)
        displayName: "Docker Build"
