name: Build and test

inputs:
  backendCsprojPath:
    required: true
  
  integrationTestsProjectPath:
    required: true
  
  unitTestsProjectPath:
    required: true
  
  buildConfiguration:
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch Sources
      uses: actions/checkout@v3

    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: NuGet Cache
      uses: actions/cache@v3
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

    - name: Restore Nuget Packages
      run: dotnet restore --verbosity minimal

    - name: Build .NET Project
      run: |
        dotnet build --no-restore /p:ContinuousIntegrationBuild=true --configuration {{ inputs.buildConfiguration }}

    - name: Run unit tests
      run: |
        dotnet test {{ inputs.unitTestsProjectPath }} --configuration {{ inputs.buildConfiguration }}

    - name: Run integration tests
      run: |
        dotnet test {{ inputs.integrationTestsProjectPath }} --configuration {{ inputs.buildConfiguration }}

    - name: Publish .NET Project
      run: |
        dotnet publish "{{ inputs.backendCsprojPath }}" --configuration "{{ inputs.buildConfiguration }}" --output "publish"

    - name: Drop Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'drop'
        path: 'publish'